#!/usr/bin/env python3

import os
from pathlib import Path
from twitter_tools import dl_tweet_tree_images

if __name__ == '__main__':
    from dotenv import load_dotenv
    load_dotenv()

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('tweet_id', type=str)
    parser.add_argument('--output_dir', type=str, default='twitter')
    parser.add_argument('--token', type=str, default=os.environ.get('TOKEN'))
    args = parser.parse_args()

    tweet_id = args.tweet_id
    output_dir = Path(args.output_dir)
    token = args.token

    dl_tweet_tree_images(tweet_id=tweet_id, output_dir=output_dir, token=token)
